# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O4G7ts0dIH59Ry01T3TZ869ULFFWYJk5
"""

#horizontal position of knight BUNA DOOKUNMA
import sys 
horizontal_knight = input("Please enter horizontal position of the knight (a,b,c,d,e,f,g,h): ").lower()  #.lower()
s1 = ("a", "b", "c", "d", "e", "f", "g","h")
s2 = ('i', 'j', 'k','m', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',)
if horizontal_knight in s2:
  print("Horizontal input for knight is not a proper letter")
elif len(horizontal_knight)!=1 or horizontal_knight.isdigit() :
  print("Horizontal input for knight is not a letter") 
elif horizontal_knight in s1:
  
  # vertical position of the knight 
  n1 = ["1","2","3","4","5","6","7","8"]
  vertical_knight =input("Please enter vertical position of the knight (1,2,3,4,5,6,7,8): ")
  vertical_knight1 = vertical_knight.isalpha()
  if vertical_knight1 == True:
    print("Vertical input for knight is not a number")
  elif vertical_knight not in n1:
    print("Vertical input for knight is not a proper number")
  elif vertical_knight in n1:
    #horizontal position of bishop
    horizontal_bishop = input("Please enter horizontal position of the bishop (a,b,c,d,e,f,g,h): ").lower() 
    if horizontal_bishop in s2:
      print("Horizontal input for bishop is not a proper letter")
    elif len(horizontal_bishop) !=1 or horizontal_bishop.isdigit() :
      print("Horizontal input for bishop is not a letter")
    elif horizontal_bishop in s1:
      #vertical position of bishop 
      vertical_bishop = (input("Please enter vertical position of the bishop (1,2,3,4,5,6,7,8): "))
      vertical_bishop1 = vertical_knight.isalpha()
      if vertical_bishop == True:
        print("Vertical input for bishop is not a number")
      elif vertical_knight not in n1:
        
        print("Vertical input for knight is not a proper number")
      elif vertical_bishop in n1:

        #other conditions :
        if (horizontal_knight == horizontal_bishop) and (vertical_knight == vertical_bishop):
          print("They can't be in the same square")
        elif abs(ord(horizontal_bishop)) - (ord(horizontal_knight)) == abs((vertical_bishop) - (vertical_knight)):
          print("Bishop can attack knight")
        elif abs(ord(horizontal_bishop) - ord(horizontal_knight)) ==1 and abs(vertical_bishop - vertical_knight) == 2:
          print("Knight can attack bishop")
        elif abs(ord(horizontal_bishop) - ord(horizontal_knight)) == 2 and abs(vertical_bishop - vertical_knight)==1:
          print("Knight can attack bishop")
        else:
          print("Neither of them can attack each other")

mylist2 = ["-","?","*","_","!","/","#","$","½"]
horiknight = input("Please enter horizontal position of the knight (a,b,c,d,e,f,g,h): ").lower()
if horiknight in mylist2:
  print("Horizontal input for knight is not a letter")
horizontal_knight1 = horiknight.isdigit()
if horizontal_knight1 == True:
  print("Horizontal input for knight is not a letter")




chrlist = ('i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z')
chrlist2 = ("a", "b", "c", "d", "e", "f", "g","h")
if horiknight in chrlist:
  print("Horizontal input for knight is not a proper letter")
elif len(horiknight)!=1:
  print("Horizontal input for knight is not a letter") 
elif horiknight in chrlist2:
  
  vertiknight = input("Please enter vertical position of the knight (1,2,3,4,5,6,7,8): ")
  if vertiknight in mylist2:
    print("Vertical input for knight is not a number")
  ab = ("1","2","3","4","5","6","7","8")
  vertical_knight1 = vertiknight.isalpha()

  if vertical_knight1 == True:
    print("Vertical input for knight is not a number")
  
  elif vertiknight not in ab:    
    print("Vertical input for knight is not a proper number")
  elif vertiknight in ab:
   
    horibish = input("Please enter horizontal position of the bishop (a,b,c,d,e,f,g,h): ").lower()
    if horibish in mylist2:
      print("Horizontal input for bishop is not a letter")
    horizontal_bishop1 = horibish.isdigit()
    if horizontal_bishop1 == True:
      print("Horizontal input for bishop is not a letter")
 
    
    if horibish in chrlist:
      print("Horizontal input for bishop is not a proper letter")
    elif len(horibish) !=1 or horibish.isdigit() :
      print("Horizontal input for bishop is not a letter")
    elif horibish in chrlist2:
      vertibish = input("Please enter vertical position of the bishop (1,2,3,4,5,6,7,8): ")
      if vertibish in mylist2:
        print("Vertical input for bishop is not a number")
      n1 = ("1","2","3","4","5","6","7","8")
      vertical_bishop1 = vertibish.isalpha()

      if vertical_bishop1 == True:
       print("Vertical input for bishop is not a number")
      elif vertiknight not in ab:
       print("Vertical input for knight is not a proper number")
      
      elif vertiknight in ab:
        if vertibish == "-":
          vertibish = 99
        elif vertibish == "1":
          vertibish = 1
        elif vertibish == "2":
            vertibish = 2
        elif vertibish == "3":
          vertibish = 3
        elif vertibish == "4":
          vertibish = 4
        elif vertibish == "5":
          vertibish = 5
        elif vertibish == "6":
          vertibish = 6
        elif vertibish == "7":
          vertibish = 7
        elif vertibish == "8":
          vertibish = 8
      if vertiknight == "1":
        vertiknight = 1
      elif vertiknight == "2":
        vertiknight = 2
      elif vertiknight == "3":
        vertiknight = 3
      elif vertiknight == "4":
        vertiknight = 4
      elif vertiknight == "5":
           vertiknight = 5
      elif vertiknight == "6":
        vertiknight = 6
      elif vertiknight == "7":
        vertiknight = 7
      elif vertiknight == "8":
        vertical = 8
      if horibish == "a":
        horibish = 1
      elif horibish == "b":
        horibish = 2
      elif horibish == "c":
        horibish = 3
      elif horibish == "d":
        horibish = 4
      elif horibish == "e":
        horibish = 5
      elif horibish == "f":
        horibish = 6
      elif horibish == "g":
        horibish = 7
      elif horibish == "h":
        horibish = 8
      
      if horiknight == "a":
        horiknight = 1
      elif horiknight == "b":
        horiknight = 2
      elif horiknight == "c":
        horiknight = 3
      elif horiknight == "d":
        horiknight = 4
      elif horiknight == "e":
        horiknight = 5
      elif horiknight == "f":
        horiknight = 6
      elif horiknight == "g":
        horiknight = 7
      elif horiknight == "h":
        horiknight = 8
      if horiknight == horibish and vertiknight == vertibish:
        print("They can't be in the same square")
    


      elif abs(((horibish)) - (horiknight)) == abs(vertibish - vertiknight):
        print("Bishop can attack knight")
      elif abs(((horibish)) - (horiknight)) ==1 and abs(vertibish - vertiknight) == 2 :
        print("Knight can attack bishop")
      elif abs(((horibish)) - (horiknight)) == 2 and abs(vertibish - vertiknight)==1:
        print("Knight can attack bishop")
      elif vertibish == 99:
        print()
         
      else:
        print("Neither of them can attack each other")

mylist2 = ["-","?","*","_","!","/","#","$","½"]
horiknight = input("Please enter horizontal position of the knight (a,b,c,d,e,f,g,h): ").lower()
if len(horiknight) > 1:
      print("Horizontal input for knight is not a letter")
horizontalknight = horiknight.isdigit()
list1 = ["a","b","c","d","e","f","g","h"]
chrlist = ('i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z')
if horiknight in chrlist:
  print("Horizontal input for knight is not a proper letter")
elif horizontalknight == True:
  print("Horizontal input for knight is not a letter") 
elif horiknight in list1:
  vertiknight = (input("Please enter vertical position of the knight (1,2,3,4,5,6,7,8): ")) 

  verticalknight = vertiknight.isalpha()
  if verticalknight == True:
    print("Vertical input for knight is not a number")
  elif verticalknight == False and int((vertiknight)) < 1 or int(vertiknight) > 8:
    print("Vertical input for knight is not a proper number")
  elif verticalknight == False and int(vertiknight) > 0 and int(vertiknight) < 9:
    horibish = input("Please enter horizontal position of the bishop (a,b,c,d,e,f,g,h): ").lower()
    if len(horibish) > 1:
      print("Horizontal input for bishop is not a letter")
 
    horizontalbishop = horibish.isdigit()
    if horizontalbishop == True:
      print("Horizontal input for bishop is not a letter")
    elif horizontalbishop == False: 

      horizontalbishop = horibish.isdigit()
      if horibish in chrlist:
        print("Horizontal input for bishop is not a proper letter")
      elif horibish in list1:
        vertibish = (input("Please enter vertical position of the bishop (1,2,3,4,5,6,7,8): "))
        numbers = ("1","2","3","4","5","6","7","8")
        verticalbishop = vertibish.isalpha()
        if vertibish in mylist2:
          print("Vertical input for bishop is not a number")
        elif verticalbishop == True:
          print("Vertical input for bishop is not a number")
        elif vertiknight not in numbers:
          print("Vertical input for knight is not a proper number")
          
        elif ord(horiknight) == ord(horibish) and vertiknight == vertibish:
          print("They can't be in the same square")
        elif abs(ord(horibish) - ord(horiknight)) == abs(int(vertibish) - int(vertiknight)):
          print("Bishop can attack knight")
        elif abs(ord(horibish) - ord(horiknight)) ==1 and abs(int(vertibish) - int(vertiknight)) == 2 :
          print("Knight can attack bishop")
        elif abs(ord(horibish) - ord(horiknight)) == 2 and abs(int(vertibish) - int(vertiknight))==1:
          print("Knight can attack bishop")
        else:
          print("Neither of them can attack each other")

print(check1)

mylist2 = ["-","?","*","_","!","/","#","$","½"]
horiknight = input("Please enter horizontal position of the knight (a,b,c,d,e,f,g,h): ").lower()
if len(horiknight) > 1:
      print("Horizontal input for knight is not a letter")
horizontalknight = horiknight.isdigit()
list1 = ["a","b","c","d","e","f","g","h"]
chrlist = ('i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z')
if horiknight in chrlist:
  print("Horizontal input for knight is not a proper letter")
elif horizontalknight == True:
  print("Horizontal input for knight is not a letter") 
elif horiknight in list1:
  vertiknight = (input("Please enter vertical position of the knight (1,2,3,4,5,6,7,8): ")) 

  verticalknight = vertiknight.isalpha()
  if verticalknight == True:
    print("Vertical input for knight is not a number")
  elif verticalknight == False and int((vertiknight)) < 1 or int(vertiknight) > 8:
    print("Vertical input for knight is not a proper number")
  elif verticalknight == False and int(vertiknight) > 0 and int(vertiknight) < 9:
    horibish = input("Please enter horizontal position of the bishop (a,b,c,d,e,f,g,h): ").lower()
    if len(horibish) > 1:
      print("Horizontal input for bishop is not a letter")
 
    horizontalbishop = horibish.isdigit()
    if horizontalbishop == True:
      print("Horizontal input for bishop is not a letter")
    elif horizontalbishop == False: 

      horizontalbishop = horibish.isdigit()
      if horibish in chrlist:
        print("Horizontal input for bishop is not a proper letter")
      elif horibish in list1:
        vertibish = (input("Please enter vertical position of the bishop (1,2,3,4,5,6,7,8): "))
        check1 = vertibish
        def check1():
          type(check1)
          if type(check1) != type("a"):
            print("Vertical input for bishop is not a number")
        numbers = ("1","2","3","4","5","6","7","8")
        verticalbishop = vertibish.isalpha()

  
          

        if vertibish in mylist2:
          print("Vertical input for bishop is not a number")
        elif verticalbishop == True:
          print("Vertical input for bishop is not a number")
        elif vertiknight not in numbers:
          print("Vertical input for knight is not a proper number")
          
        elif ord(horiknight) == ord(horibish) and vertiknight == vertibish:
          print("They can't be in the same square")
        elif abs(ord(horibish) - ord(horiknight)) == abs(int(vertibish) - int(vertiknight)):
          print("Bishop can attack knight")
        elif abs(ord(horibish) - ord(horiknight)) ==1 and abs(int(vertibish) - int(vertiknight)) == 2 :
          print("Knight can attack bishop")
        elif abs(ord(horibish) - ord(horiknight)) == 2 and abs(int(vertibish) - int(vertiknight))==1:
          print("Knight can attack bishop")
        else:
          print("Neither of them can attack each other")

print(check1)